Version 6.0.0 - Route Storing
cevi/automatic_walk-time_tables pull request #457
Opened 2024-08-04 14:46 UTC by maede97

This PR tracks the work needed to implement route storing.

This is needed for: 
- [ ] #422 
- [ ] #358 

possible extensions:
- #410 
- #380
- #379
- #378
- #173
- #146

2024-08-04 15:16 UTC, maede97 commented
See also #458

2024-08-04 16:44 UTC, maede97 commented
WIP: https://github.com/cevi/automatic_walk-time_tables/tree/feature/route-storing

2024-10-01 07:21 UTC, wp99cp commented
We can postpone the remaining todos to a later release. We still need to test the new features carefully, but then we should be ready for version 6.0.0.

2024-10-02 09:25 UTC, wp99cp requested changes

2024-10-02 09:25 UTC, wp99cp commented on .env.prod-dev
> +MONGO_INITDB_ROOT_PASSWORD=pass
We should consider leaving the password empty and not starting the container without that env variable to force the user to set its own password and don‘t use our default password

2024-10-02 09:25 UTC, wp99cp commented on .env.prod-latest
> +MONGO_INITDB_ROOT_PASSWORD=pass
We should consider leaving the password empty and not starting the container without that env variable to force the user to set its own password and don‘t use our default password

2024-10-02 09:25 UTC, wp99cp commented on backend/automatic_walk_time_tables/utils/path.py
> +from .way_point import WayPoint, way_point_from_json
We should consider using package imports instead of relative imports (see other files)

2024-10-02 09:25 UTC, wp99cp commented on route_engine/Dockerfile
See #499

2024-10-02 19:34 UTC, wp99cp approved these changes

2024-10-02 20:28 UTC, wp99cp approved these changes

2024-10-02 20:28 UTC, wp99cp approved these changes

2024-10-03 09:11 UTC, merged